feat: if could not checkout to specific commit, stay on latest one

diff --git a/scripts/Containerfile-jar-gis b/scripts/Containerfile-jar-gis
--- a/scripts/Containerfile-jar-gis
+++ b/scripts/Containerfile-jar-gis
@@ -4,5 +4,5 @@ RUN apk add --no-cache git
 RUN git clone https://github.com/nqminhuit/gis.git /app/gis
 WORKDIR /app/gis
 RUN git log --pretty=oneline -n 20
-RUN git reset --hard "$GIS_COMMIT"
+RUN git checkout "$GIS_COMMIT" || echo "invalid commit, stay on latest"
 RUN mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean package
